### ISSUE TITLE
New to this so bear with me!

### ISSUE THREAD

**Issue by NewGuy20** [keydet89/RegRipper3.0#6] opened 2020-08-06 04:32 UTC
I was trying to use RegRipper and was stuck with a strange error message. I downloaded it from here, and no where else. I tried it on a Virtual Machine, and my host machine. Got the same error @ line 492 on both machines. Please advise as this is an issue that does not seem to be documented.

What the message says, " Can't call method "is_dirty" on an undefined value at C:\Users\[redacted]\Downloads\RegRipper3.0-master\RegRipper3.0-master\rr.exe line 492."

Was not able to include the screen shot!!!

**Comment by keydet89** [comment] 2020-08-06 12:11
What is the path to the hive file you were attempting to run RR against?  

Thanks!

**Comment by NewGuy20** [comment] 2020-08-06 13:41
Hello,

I started with Computer\HKEY_LOCAL_MACHINE\SYSTEM. Then I tried it with Computer\HKEY_LOCAL_MACHINE\SECURITY. I exported them both, and got the same error message.

Thank you for replying so quickly!

**Comment by keydet89** [comment] 2020-08-06 13:48
RegRipper is intended to be run against offline Registry hive files...not on live systems, and not against exported contents.

To run RR in the use case you're looking at, use the following command:

reg save HKLM\System c:\temp\system

Then run RR against the file "c:\temp\system"

**Comment by MrHobbits** [comment] 2020-12-27 02:17
Safe to close this issue then?

**Comment by keydet89** [comment] 2020-12-27 12:36
That's not up to me...that's up to NewGuy20.  

Why?

**Comment by MrHobbits** [comment] 2020-12-28 17:56
Can't you mark the issue as closed? I only recommend closure as OP hasn't responded in 5 months, has no other contributions/repositories, and the issue isn't with RR itself. It appears to be a 'use' issue rather than a 'bug' issue.

**Closed** 2021-06-23 14:25 UTC
